site_name: JJ's Bakery
nav:
  - Old Testament:
    - Genesis
    - Exodus
    - Leviticus
    - Numbers
    - Deuteronomy
    - Joshua
    - Judges
    - Ruth
    - 1 Samuel
    - 2 Samuel
    - 1 Kings
    - 2 Kings
    - 1 Chronicles
    - 2 Chronicles
    - Ezra
    - Nehemiah
    - Esther
    - Job
    - Psalms
    - Proverbs
    - Ecclesiastes
    - Song of Solomon
    - Isaiah
    - Jeremiah
    - Lamentations
    - Ezekiel
    - Daniel
    - Hosea
    - Joel
    - Amos
    - Obadiah
    - Jonah
    - Micah
    - Nahum
    - Habakkuk
    - Zephaniah
    - Haggai
    - Zechariah
    - Malachi
  - New Testament
    - Matthew
    - Mark
    - Luke
    - John
    - Acts
    - Romans
    - 1 Corinthians
    - 2 Corinthians
    - Galatians
    - Ephesians
    - Philippians
    - Colossians
    - 1 Thessalonians
    - 2 Thessalonians
    - 1 Timothy
    -  2 Timothy
    - Titus
    - Philemon
    - Hebrews
    - James
    -  1 Peter
    - 2 Peter
    - 1 John
    - 2 John
    - 3 John
    - Jude
    - Revelation
- Reading Journals
- Topics
theme:
    name: 'material'
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
